### ISSUE TITLE
Debugging broken in latest VS Code

### ISSUE THREAD

**Issue by robertcoltheart** [microsoft/azuredatastudio-debug#19]
When launching a debug session with the default `yo` generated extension for AZ Data studio, the following error occurs:

```
Error processing "launch": Error: spawn EINVAL
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at Object.spawn (node:child_process:795:9)
    at NodeDebugAdapter.launchInInternalConsole (c:\Users\rober\.vscode\extensions\ms-mssql.sqlops-debug-1.4.0\out\src\nodeDebugAdapter.js:481:32)
    at NodeDebugAdapter.extensionHostLaunch (c:\Users\rober\.vscode\extensions\ms-mssql.sqlops-debug-1.4.0\out\src\nodeDebugAdapter.js:356:21)
    at NodeDebugAdapter.<anonymous> (c:\Users\rober\.vscode\extensions\ms-mssql.sqlops-debug-1.4.0\out\src\nodeDebugAdapter.js:186:29)
    at Generator.next (<anonymous>)
    at fulfilled (c:\Users\rober\.vscode\extensions\ms-mssql.sqlops-debug-1.4.0\out\src\nodeDebugAdapter.js:8:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Possibly related to the requirement for `shell` to be added to spawning child processes in nodejs.

Edit: The workaround for this is to create your extension in a path that has spaces in it, eg `c:\my project\azextension`, which forces the debug spawner to use `shell` [here](https://github.com/microsoft/azuredatastudio-debug/blob/main/src/nodeDebugAdapter.ts#L545).

@Charles-Gagnon @kisantia @roblourens

**Comment by robertcoltheart** [comment]
Is this plugin still maintained?
